version: '3'
services:
    app:
        build: './docker/app'
        links:
            - db
        volumes:
            - '.:/var/www/app:cached'
        ports:
            - '8000:8000'
        environment:
            DATABASE_URL: 'mysql://root@db/app'
            MESSENGER_TRANSPORT_DSN: amqp://guest:guest@queue:5672/%2f/messages

    db:
        build: './docker/mysql/'
        image: mysql:5.7
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: app
            MYSQL_USER: root
            MYSQL_ALLOW_EMPTY_PASSWORD: '1'
        command:
            - 'mysqld'
            - '--character-set-server=utf8mb4'
            - '--collation-server=utf8mb4_unicode_ci'
            - '--default-authentication-plugin=mysql_native_password'