<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAfww5kh\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAfww5kh/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAfww5kh.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAfww5kh\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerAfww5kh\srcDevDebugProjectContainer([
    'container.build_hash' => 'Afww5kh',
    'container.build_id' => '213a1e92',
    'container.build_time' => 1584565367,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAfww5kh');
